USE hotell;

DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Invoices;
DROP TABLE IF EXISTS CancellationRefund;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Notifications;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Users;

